### ISSUE TITLE
Fuzzy heatmap

### ISSUE THREAD

**Issue by tiramisutes** [mrvollger/StainedGlass#11]
Hi,
I input the whole chromosome sequence with 10bk windows to run this Snakemake. As you can see, the output heatmap is blurry. So how can I make it clear? Is it to set a larger or smaller window or other parameters?
![image](https://user-images.githubusercontent.com/10768210/169726803-ef354ccf-1d7b-4876-9c79-008edbd7a1c4.png)
Any help is much appreciated.
Thanks.

Best regards,

**Comment by mrvollger** [comment]
For whole chromosome views you need to use HiGlass:
https://github.com/mrvollger/StainedGlass#visualization-of-a-large-region-or-a-whole-genome

This image is trying to represent significantly more points than there are pixels on any reasonable screen, so the png view is unreliable, and that maybe why most points are averaging to white, though I am not sure.

**Comment by tiramisutes** [comment]
Thanks. I get it. I will try using HiGlass.
