### ISSUE TITLE
snakemake : Downloading and installing remote packages.

### ISSUE THREAD

**Issue by JiaoLaboratory** [mrvollger/StainedGlass#13]
Dear [StainedGlass] developer,
snakemake --use-conda --cores 24
Thanks for using StainedGlass and please remember to cite the tool!
    Mitchell R Vollger, Peter Kerpedjiev, Adam M Phillippy, Evan E Eichler.
            "StainedGlass: Interactive visualization of massive tandem repeat structures with identity heatmaps"
            Bioinformatics, 2022; https://doi.org/10.1093/bioinformatics/btac018

[INFO] The sequence will be split into 4 batches.
Building DAG of jobs...
Removing incomplete Conda environment workflow/envs/env.yaml...
Creating conda environment workflow/envs/env.yaml...
Downloading and installing remote packages.
...

I do not know why stop here ? could you help me

**Comment by mrvollger** [comment]
I don't see an error here, only progress statements, so I cannot be of much help. Can you send the complete log with the error message?

Mitchell

**Comment by mrvollger** [comment]
Closed due to inactivity.
