### ISSUE TITLE
install env.yaml and R.yaml once

### ISSUE THREAD

**Issue by zy041225** [mrvollger/StainedGlass#17]
Dear author,

I'm trying StainedGlass and have successfully created one figure with my sequences. However, when I tried to visualize another plot in another directory, it seems that StainedGlass need to download and create the environment again. I wonder if it is possible to create the environment just for one time, and then use this in latter analysis. Generally I don't have the internet access on the HPC. 

Many thanks

Best,
Yang

**Comment by mrvollger** [comment]
Hi Yang,

This is a reasonable request and snakemake very recently made this possible. However I don't have much time at the moment. Happy to look over a PR if you feel inclined, but either way I will leave this open till I get a chance to look at it.

Cheers,
Mitchell

**Comment by mrvollger** [comment]
I recently learned about the `--conda-prefix` option in snakemake.
```
--conda-prefix
Specify a directory in which the ‘conda’ and ‘conda-archive’ directories are created. These are used to store conda environments and their archives, respectively. If not supplied, the value is set to the ‘.snakemake’ directory relative to the invocation directory. If supplied, the –use-conda flag must also be set. The value may be given as a relative path, which will be extrapolated to the invocation directory, or as an absolute path. The value can also be provided via the environment variable $SNAKEMAKE_CONDA_PREFIX.
```
which will allow you to set one share install location of all the snakemake environments. 

https://snakemake.readthedocs.io/en/stable/executing/cli.html

Using this should solve your issue.
