### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by shdonghzau** [mrvollger/StainedGlass#20]
Dear author,
When I install StainedGlass, and run with the tested Arabidopsis genome. The program exits because a job execution failed.  The log file is in the attachment.  Could you please help sovle it? 

Many thanks!  

Best,
[2023-01-12T181630.196561.snakemake.log](https://github.com/mrvollger/StainedGlass/files/10423094/2023-01-12T181630.196561.snakemake.log)

Handong

**Comment by mrvollger** [comment]
Can you include the logs of the rules that failed to run, e.g.:
```
logs/aln.arabidopsis.2000.10000.0.ref_0.log 
```

**Comment by shdonghzau** [comment]
[aln.arabidopsis.2000.10000.0.ref_0.log](https://github.com/mrvollger/StainedGlass/files/10454163/aln.arabidopsis.2000.10000.0.ref_0.log)
[aln.arabidopsis.2000.10000.1.ref_0.log](https://github.com/mrvollger/StainedGlass/files/10454164/aln.arabidopsis.2000.10000.1.ref_0.log)
[aln.arabidopsis.2000.10000.2.ref_0.log](https://github.com/mrvollger/StainedGlass/files/10454166/aln.arabidopsis.2000.10000.2.ref_0.log)

**Comment by mrvollger** [comment]
The log files say the job was killed which nearly always means your machine doesn't have enough available ram for the task. You could try `--cores 4`  or lower to limit the number of simultaneous jobs or you could use a machine with more ram. My guess is that you will need the machine with more ram.
