### ISSUE TITLE
No .bed files created

### ISSUE THREAD

**Issue by Evansd36** [mrvollger/StainedGlass#22]
Hello Authors!

Thank you for making such a cool program! 

I have been trying to make a figure based on a whole genome fasta. I ran the code below and the program ran for ~an hour but didn't actually make any .bed or .bam files in the /temp directory or /results directory. I have attached the run log and was curious if you would be willing to help me identify what went wrong.

I am working on a weird server that is being re-made as I use it meaning I have to explicitly specify where files are so there may be a bit of extra code sprinkled around. It is also quite possible that due to the state of the server, something didn't fully download correctly (snakemake or stainedglass). Any help would be appreciated and let me know if you need any additional files thanks!!

-Evan Stark-Dykema 

Run log

[2023-03-08T120306.471184.snakemake.log](https://github.com/mrvollger/StainedGlass/files/10925729/2023-03-08T120306.471184.snakemake.log)

Snakefile (not actually a .txt just had to add that to upload to github)

[Snakefile.txt](https://github.com/mrvollger/StainedGlass/files/10925749/Snakefile.txt)

Code I ran 

snakemake -s /mnt/beegfs/es180966/StainedGlass/workflow/Snakefile --use-conda --cores 24 --config sample=guttatus fasta=/mnt/beegfs/es180966/Mimulus_guttatus_var_IM62_mainGenome_withmito.fa

**Comment by mrvollger** [comment]
According to the log there was `Error in rule aln`. This most often happens when you run out of memory. 

You can check the logs for the specific rules to learn more about what specifically went wrong in that step.

**Comment by mrvollger** [comment]
closed due to inactivity.
