### ISSUE TITLE
Clarification for the `mm_f` config parameter

### ISSUE THREAD

**Issue by taprs** [mrvollger/StainedGlass#23]
Hi Mitchell,

thank you for the amazing tool!

The description for the `mm_f` config parameter probably needs to be updated. In both versions of `minimap2` I can instantly access the `-f` option only accepts floats:

```
minimap2 -V
# 2.20-r1061

minimap2 --help
# ...
# -f FLOAT     filter out top FLOAT fraction of repetitive minimizers [0.0002]
```

What parameter of the new `minimap2` corresponds to the `mm_f` parameter?

**Comment by mrvollger** [comment]
The help page is incomplete and the man page has the full description:

https://lh3.github.io/minimap2/minimap2.html

Also note this pipeline forces minimap2 v2.18. 

Best,
Mitchell

**Comment by taprs** [comment]
Got it, thanks!
