### ISSUE TITLE
container availablity?

### ISSUE THREAD

**Issue by aseetharam** [mrvollger/StainedGlass#25]
Hello,

I was wondering if you have a container (singularity/docker) available for the `StainedGlass`.  
Provided `conda` fails to resolve all requirements correctly and when installed manually some packages does not work with other versions.

 ```
cload.py", line 551, in pairs
    f_in = get_handle(pairs_path, mode='r', compression='infer')[0]
TypeError: 'IOHandles' object is not subscriptable
```
could you please revise the recipe or provide a container for running this?

Thanks!

**Comment by mrvollger** [comment]
I am not an expert in containers because my HPC doesn't allow them. However, I'd be happy to consider/help with a pull request that integrates this feature. 

Best,
Mitchell

**Comment by mrvollger** [comment]
I added a dockerfile that I think should resolve this issue.

**Comment by mrvollger** [comment]
I added a Dockerfile that I think resolves this issue
