### ISSUE TITLE
pandas<2 needed to handle cooler issue

### ISSUE THREAD

**Issue by amakunin** [mrvollger/StainedGlass#26]
Hi, thanks for the software - works really smoothly! I'd like to report small weirdness that might be related to my particular setup:

An old reported cooler error (https://github.com/open2c/cooler/issues/248) arose when using `cooler_density` mode, pandas 2.0.2 was installed by conda in that case. After tweaking the environment to have `- pandas<2` the error was resolved and the workflow completed successfully.

**Comment by mrvollger** [comment]
Awesome thanks! Can you tell me your specific cooler and pandas version in your conda env so I can lock the versions in the env file?

**Comment by amakunin** [comment]
The installation that worked had
```
  - cooler=0.9.1
  - pandas=1.5.3
  - python=3.10.11
```
My guess is that only pandas being below v2 is important, but I'm not entirely sure, tbh

**Comment by mrvollger** [comment]
Thanks! I am going to go with locking in versions we know work.
