### ISSUE TITLE
solutions for larger chromosomes? 

### ISSUE THREAD

**Issue by laramiemckenna** [mrvollger/StainedGlass#31]
Hi there! I'm trying to use StainedGlass to visualize some _very very very_ large plant chromosomes (400+ Mbp). Whenever the chromosome size gets above 120 Mbp or so, I start to encounter memory limitations, specifically the following error whenever it hits `rule aln`:

```
Error in rule aln:
    jobid: 0
    input: temp/scaffold_10_hap1.2000.10000.ref_0.fasta.mmi, temp/scaffold_10_hap1.2000.3.query.fasta
    output: temp/scaffold_10_hap1.2000.10000.3.ref_0.bam
    log: logs/aln.scaffold_10_hap1.2000.10000.3.ref_0.log (check log file(s) for error details)
    conda-env: /cluster/home/lasmith/stained_glass/hap1/scaffold_10/StainedGlass/.snakemake/conda/a354342b3663b5405bcdaaaf91e3aee9_
    shell:

	( minimap2             -t 1             -f 10000 -s 400             -ax ava-ont              --dual=yes --eqx             temp/scaffold_10_hap1.2000.10000.ref_0.fasta.mmi temp/scaffold_10_hap1.2000.3.query.fasta     $

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
slurmstepd: error: Detected 1 oom_kill event in StepId=1685290.batch. Some of the step tasks have been OOM Killed.
```
I've tried throwing as many resources as I can think of at it: increasing the thread # and memory requirements for batch jobs in the Snakefile, specifying more `--cores`, and modifying the $SBATCH options. 

Do you have any suggestions for how I can optimize my StainedGlass run to account for these massive chromosomes?

**Comment by mrvollger** [comment]
Sorry, but my only idea is more memory and more time. 

I know I have many times done this on human chromosomes (which max out at ~250 Mbp) and the solution there was always just more mem.
