### ISSUE TITLE
cool file

### ISSUE THREAD

**Issue by molecule53** [mrvollger/StainedGlass#39]
Hello again,

Sorry for bombarding...
I got the first part working and generated files below. I can't figure out what command to run to get the .mcool file to view in resgen.io

(snakemake) [@c15 StainedGlass]$ cd results/
(snakemake) [@c15 results]$ ls
NOR2.2000.10000.bed.gz  NOR2.2000.10000.full.tbl.gz  NOR2.2000.10000.sorted.bam  NOR2.2000.10000.sorted.bam.csi  NOR2.2000.fasta

When I am adding 'cooler' command (as below), I am getting an error:
(snakemake) [@c15 StainedGlass]$ time snakemake --cores 8 --config sample=NOR2
fasta=../NOR2.fasta cooler
Traceback (most recent call last):
  File "/geode2/home/u015/anasgrid/Quartz/miniforge3/envs/snakemake/lib/python3.12/site-packages/snakemake/common/__init__.py", line 65, in parse_key_value_arg
    key, val = arg.split("=", 1)
    ^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by mrvollger** [comment]
Snakemake is interpreting "cooler" as a config option instead of a target. Try just moving it just before the --config argument.

**Comment by molecule53** [comment]
Thank you very much, Mitchell! Everything works now! I will close this issue.
