### ISSUE TITLE
Apple M2 installation problems

### ISSUE THREAD

**Issue by hendersi** [mrvollger/StainedGlass#44]
I'm having difficulty running StainedGlass on a MacBookPro Apple M2 Max macOS Sonoma.

I followed the installation instructions, but when I run the command 

snakemake --cores all --use-conda

I obtain the following errors 

Thanks for using StainedGlass and please remember to cite the tool!
    Mitchell R Vollger, Peter Kerpedjiev, Adam M Phillippy, Evan E Eichler.
            "StainedGlass: Interactive visualization of massive tandem repeat structures with identity heatmaps"
            Bioinformatics, 2022; https://doi.org/10.1093/bioinformatics/btac018
[INFO] The sequence will be split into 4 batches.
Assuming unrestricted shared filesystem usage.
Building DAG of jobs...
Creating conda environment https://raw.githubusercontent.com/mrvollger/StainedGlass/v0.6/workflow/envs/env.yaml...
Downloading and installing remote packages.
CreateCondaEnvironmentException:
Could not create conda environment from /var/folders/6z/dbjpst5x7hx744d90zzkd44m0000gp/T/tmpw95wass_.yaml:
Command:
mamba env create --quiet --no-default-packages --file "/Users/irh25/Documents/software/test/.snakemake/conda/1dfc8f3ae74d3d6f467a9914772f6855_.yaml" --prefix "/Users/irh25/Documents/software/test/.snakemake/conda/1dfc8f3ae74d3d6f467a9914772f6855_"
Output:
Channels:
 - conda-forge
 - bioconda
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed
Channels:
 - conda-forge
 - bioconda
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides requested bioconda::samtools >=1.14
  - nothing provides requested bioconda::pysam >=0.15.0
  - nothing provides requested bioconda::htslib >=1.14
  - nothing provides requested bioconda::bwa
  - nothing provides requested bioconda::bedtools
  - nothing provides requested minimap2 2.18
  - nothing provides pairix needed by cooler-0.7.6-pyh1341992_2

Could not solve for environment specs
The following packages are incompatible
├─ bedtools does not exist (perhaps a typo or a missing channel);
├─ bwa does not exist (perhaps a typo or a missing channel);
├─ cooler <=0.8.11  is not installable because there are no viable options
│  ├─ cooler [0.7.6|0.8.11|0.8.6] would require
│  │  └─ pairix, which does not exist (perhaps a missing channel);
│  └─ cooler [0.8.10|0.8.11|0.8.7|0.8.8|0.8.9] would require
│     └─ biopython <1.77 , which does not exist (perhaps a missing channel);
├─ htslib >=1.14  does not exist (perhaps a typo or a missing channel);
├─ minimap2 2.18  does not exist (perhaps a typo or a missing channel);
├─ pysam >=0.15.0  does not exist (perhaps a typo or a missing channel);
└─ samtools >=1.14  does not exist (perhaps a typo or a missing channel).

**Comment by mrvollger** [comment]
Unfortunately, most (all?) bioconda packages don't exist for ARM Macs. 

I have had success with this workaround that tells Conda to use MacOS translational layer: 
```
CONDA_SUBDIR=osx-64 snakemake --cores all --use-conda
```
but I wouldn't say that I am "supporting" ARM Macs at this time. 

Good luck!
