### ISSUE TITLE
python environment

### ISSUE THREAD

**Issue by duhuipeng** [mrvollger/StainedGlass#7]
Dear author
I'm now running the centromere  file ,But now I have a problem .(as follow)
![image](https://user-images.githubusercontent.com/58722433/143375177-6d5f66e2-51ed-4eda-ab43-40f685a81a37.png)
He has been installing the required dependency packages,In fact, I've already installed them.At this point, I look at his Python path,
I discovered that it was not the python from which I installed all the dependency packages.(as follow)
![image](https://user-images.githubusercontent.com/58722433/143375565-1f07fc4d-86e1-4f06-b3a4-c744e721425c.png)
(This is the python path it uses)
Actually my path to install all the package dependent python is as follows
![image](https://user-images.githubusercontent.com/58722433/143375891-3aa4ae4c-b1bf-44ad-ac32-d5aa373d4c8c.png)
I thought it was a problem with my default python, but I changed the version of the default python to the required python3.9.(as follow)
![image](https://user-images.githubusercontent.com/58722433/143376355-04033a9e-465b-488b-8917-0828f5b6e790.png)
 When I was running the command of the snakemake line of code, he still had the problem, the python he called was  the original python (the first screenshot for you)

I don t know how to fix this to be able to get him to call the py3.9 this python I need.This problem has bothered me for over a day,especially hope to get your help.
Looking forward to your response

Thanks
huipeng Du

**Comment by mrvollger** [comment]
I see you closed this issue so I am going to assume you figured out how to resolve this. Hope it works out for your application!
