### ISSUE TITLE
Trouble generating figures

### ISSUE THREAD

**Issue by pilleh** [mrvollger/StainedGlass#8]
Hi,
I'm trying to run the workflow according to the manual page. The alignment step is working nicely, but not the figure generation as  it’s not able to generate the required conda environments. I’m not sure how to fix this, so I wonder if you might have any suggestions? I’m attaching the log file from the job.
Many thanks!
Pille
[StainedGlass_TEST_NA19317_DYZ19_301121-11892116.err.txt](https://github.com/mrvollger/StainedGlass/files/7635598/StainedGlass_TEST_NA19317_DYZ19_301121-11892116.err.txt)

**Comment by mrvollger** [comment]
As far as I can tell this is bad build of cython in `/home/hallap/anaconda3/envs/mamba/` since all the errors are coming from that env (and not a StainedGlass/Snakemake env). I would recomened rebuilding that env from scratch or un and reinstalling cython in that env.

**Comment by pilleh** [comment]
Thanks, I'll give it a try.

**Comment by pilleh** [comment]
Turns out that updating python in the /home/hallap/anaconda3/envs/mamba/ did the trick. Getting some very nice figures now, thanks a lot!

**Comment by mrvollger** [comment]
Great!
